### ISSUE TITLE
Whether to support the transaction？

### ISSUE THREAD

**Issue by wakerman** [usmanhalalit/pixie#65] opened 2015-03-19 15:16 UTC
hi, @usmanhalalit 
Whether to support the transaction?

**Comment by neoascetic** [comment] 2015-03-24 09:31
Duplicate of #17.

**Comment by usmanhalalit** [comment] 2015-03-28 09:43
@wakerman, sorry it's not there yet, you can manually start and end transaction. But we we'll be adding this in Pixie.

Closing as duplicate.

**Closed by usmanhalalit** 2015-03-28 09:43 UTC
